language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ibaranga/multi-client-dev -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ibaranga/multi-client-dev npm run test

after_success:
  - docker build -t ibaranga/multi-client ./client
  - docker build -t ibaranga/multi-server ./server
  - docker build -t ibaranga/multi-nginx  ./nginx
  - docker build -t ibaranga/multi-worker ./worker
  - docker login -u "$DOCKER_ID" -p "$DOCKER_PASSWORD"
  - docker push ibaranga/multi-client
  - docker push ibaranga/multi-server
  - docker push ibaranga/multi-nginx
  - docker push ibaranga/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-central-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-central-1-448425806848
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
